# -*- coding: utf-8 -*-
"""BanglaBert.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZcXtyHh1JREQ-Dvb9oGJGAUqzwLDWRsw
"""

!pip -q install -U "transformers>=4.35" "accelerate>=0.23" datasets evaluate

import numpy as np
import pandas as pd
import torch

from datasets import Dataset
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import f1_score, accuracy_score, classification_report, confusion_matrix, ConfusionMatrixDisplay

from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer,
    EarlyStoppingCallback,
    set_seed,
)

SEED = 42
set_seed(SEED)

MODEL_NAME = "csebuetnlp/banglabert"   # Bangla
MAX_LEN = 256
NUM_EPOCHS = 3
LR = 2e-5
WEIGHT_DECAY = 0.01

TRAIN_PATH = "Train.csv"
VAL_PATH   = "Validation.csv"
TEST_PATH  = "Test.csv"

train_df = pd.read_csv(TRAIN_PATH)
val_df   = pd.read_csv(VAL_PATH)
test_df  = pd.read_csv(TEST_PATH)


for df in [train_df, val_df, test_df]:
    df["headline"] = df["headline"].fillna("").astype(str)
    df["description"] = df["description"].fillna("").astype(str)
    df["text"] = (df["headline"].str.strip() + " [SEP] " + df["description"].str.strip()).str.strip()
    df["label"] = df["label"].astype(int)

print("Train:", train_df.shape, "Val:", val_df.shape, "Test:", test_df.shape)
print("Train label dist:\n", train_df["label"].value_counts())
print("Val label dist:\n", val_df["label"].value_counts())
print("Test label dist:\n", test_df["label"].value_counts())


trainval_df = pd.concat([train_df, val_df], axis=0).reset_index(drop=True)

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, use_fast=True)

def tokenize_batch(batch):
    return tokenizer(
        batch["text"],
        truncation=True,
        padding="max_length",
        max_length=MAX_LEN
    )

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=-1)
    return {
        "accuracy": accuracy_score(labels, preds),
        "macro_f1": f1_score(labels, preds, average="macro")
    }

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED)

X = trainval_df["text"].values
y = trainval_df["label"].values

fold_metrics = []

for fold, (tr_idx, va_idx) in enumerate(skf.split(X, y), 1):
    print(f"\n==================== FOLD {fold} / 5 ====================")

    df_tr = trainval_df.iloc[tr_idx].reset_index(drop=True)
    df_va = trainval_df.iloc[va_idx].reset_index(drop=True)

    ds_tr = Dataset.from_pandas(df_tr[["text", "label"]])
    ds_va = Dataset.from_pandas(df_va[["text", "label"]])

    ds_tr = ds_tr.map(tokenize_batch, batched=True)
    ds_va = ds_va.map(tokenize_batch, batched=True)

    cols_to_remove = ["text"]
    ds_tr = ds_tr.remove_columns(cols_to_remove)
    ds_va = ds_va.remove_columns(cols_to_remove)

    ds_tr = ds_tr.rename_column("label", "labels")
    ds_va = ds_va.rename_column("label", "labels")

    ds_tr.set_format("torch")
    ds_va.set_format("torch")

    model = AutoModelForSequenceClassification.from_pretrained(MODEL_NAME, num_labels=2)

    args = TrainingArguments(
        output_dir=f"./banglabert_fold_{fold}",
        eval_strategy="epoch",
        save_strategy="epoch",
        load_best_model_at_end=True,
        metric_for_best_model="macro_f1",
        greater_is_better=True,
        save_total_limit=1,

        learning_rate=LR,
        weight_decay=WEIGHT_DECAY,
        num_train_epochs=NUM_EPOCHS,

        per_device_train_batch_size=8,
        per_device_eval_batch_size=16,

        fp16=True,
        logging_steps=50,
        report_to="none",
        seed=SEED
    )

    trainer = Trainer(
        model=model,
        args=args,
        train_dataset=ds_tr,
        eval_dataset=ds_va,
        tokenizer=tokenizer,
        compute_metrics=compute_metrics,
        callbacks=[EarlyStoppingCallback(early_stopping_patience=1)]
    )

    trainer.train()
    metrics = trainer.evaluate()
    print("Fold metrics:", metrics)
    fold_metrics.append(metrics)

# Summary
macro_f1s = [m["eval_macro_f1"] for m in fold_metrics]
accs = [m["eval_accuracy"] for m in fold_metrics]

print("\n==== 5-FOLD CV SUMMARY (Train+Val) ====")
print(f"Macro-F1: mean={np.mean(macro_f1s):.4f}, std={np.std(macro_f1s):.4f}")
print(f"Accuracy: mean={np.mean(accs):.4f}, std={np.std(accs):.4f}")

ds_trval = Dataset.from_pandas(trainval_df[["text", "label"]])
ds_test  = Dataset.from_pandas(test_df[["text", "label"]])

ds_trval = ds_trval.map(tokenize_batch, batched=True).remove_columns(["text"]).rename_column("label", "labels")
ds_test  = ds_test.map(tokenize_batch, batched=True).remove_columns(["text"]).rename_column("label", "labels")

ds_trval.set_format("torch")
ds_test.set_format("torch")

final_model = AutoModelForSequenceClassification.from_pretrained(MODEL_NAME, num_labels=2)

final_args = TrainingArguments(
    output_dir="./banglabert_final",
    eval_strategy="no",
    save_strategy="no",
    learning_rate=LR,
    weight_decay=WEIGHT_DECAY,
    num_train_epochs=NUM_EPOCHS,
    per_device_train_batch_size=8,
    fp16=True,
    report_to="none",
    seed=SEED
)

final_trainer = Trainer(
    model=final_model,
    args=final_args,
    train_dataset=ds_trval,
    tokenizer=tokenizer
)

final_trainer.train()

# Predict on test
pred = final_trainer.predict(ds_test)
logits = pred.predictions
y_true = pred.label_ids
y_pred = np.argmax(logits, axis=-1)

print("==== FINAL TEST RESULTS ====")
print("Macro-F1:", f1_score(y_true, y_pred, average="macro"))
print("Accuracy:", accuracy_score(y_true, y_pred))
print(classification_report(y_true, y_pred, digits=4))

cm = confusion_matrix(y_true, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm)
disp.plot()