# -*- coding: utf-8 -*-
"""CSE437_Project v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PGOGC7rmwvDtMYMEGbNSPxg-SmJi7EH5
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

train_df = pd.read_csv('Train.csv')
val_df   = pd.read_csv('Validation.csv')
test_df  = pd.read_csv('Test.csv')

print("Train shape:", train_df.shape)
print("Validation shape:", val_df.shape)
print("Test shape:", test_df.shape)

train_df.head()

#structure and summary
train_df.describe(include='all')

# Missing values
train_df.isnull().sum()

# heatmap
plt.figure(figsize=(10,4))
sns.heatmap(train_df.isnull(), cbar=False)
plt.title("Missing Values Heatmap (Train)")
plt.show()

label_col = 'label'

train_df[label_col].value_counts()

sns.countplot(x=label_col, data=train_df)
plt.title("Fake vs Real News Distribution")
plt.show()

# Remove duplicate
train_df.drop_duplicates(inplace=True)

def clean_text(x):
    if pd.isna(x):
        return ""
    return str(x).strip().replace("\n", " ")

for df in [train_df, val_df, test_df]:
    df['headline'] = df['headline'].apply(clean_text)
    df['description'] = df['description'].apply(clean_text)

train_df[['headline','description']].head()

for df in [train_df, val_df, test_df]:
    df['text'] = df['headline'] + " " + df['description']
    df['text_length'] = df['text'].apply(len)

train_df[['text','text_length']].head()

sns.histplot(train_df['text_length'], bins=30)
plt.title("Text Length Distribution")
plt.show()

sns.boxplot(x=label_col, y='text_length', data=train_df)
plt.title("Text Length vs Class")
plt.show()

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1,2)
)

X_train_text = tfidf.fit_transform(train_df['text'])
X_val_text   = tfidf.transform(val_df['text'])
X_test_text  = tfidf.transform(test_df['text'])

X_train_text.shape, X_val_text.shape, X_test_text.shape

# from scipy.sparse import hstack

# X_train = hstack([X_train_text, train_df[['text_length']].values])
# X_val   = hstack([X_val_text,   val_df[['text_length']].values])
# X_test  = hstack([X_test_text,  test_df[['text_length']].values])

# X_train.shape, X_val.shape, X_test.shape

# from sklearn.preprocessing import StandardScaler

# scaler = StandardScaler(with_mean=False)

# X_train = scaler.fit_transform(X_train)
# X_val   = scaler.transform(X_val)
# X_test  = scaler.transform(X_test)

# X_train.shape, X_val.shape, X_test.shape

# from sklearn.feature_selection import SelectKBest, chi2

# selector = SelectKBest(score_func=chi2, k=3000)

# X_train = selector.fit_transform(X_train, train_df[label_col])
# X_val   = selector.transform(X_val)
# X_test  = selector.transform(X_test)

# X_train.shape, X_val.shape, X_test.shape

from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.metrics import f1_score, classification_report, ConfusionMatrixDisplay
import matplotlib.pyplot as plt


y_train = train_df["label"].astype(int)
y_val   = val_df["label"].astype(int)


X_train = X_train_text
X_val   = X_val_text
X_test  = X_test_text


# Model 1: Logistic Regression

lr = LogisticRegression(
    max_iter=3000,
    solver="saga",
    class_weight="balanced",
    n_jobs=-1
)
lr.fit(X_train, y_train)
pred_val_lr = lr.predict(X_val)

print("=== Logistic Regression (VAL) ===")
print("Macro-F1:", f1_score(y_val, pred_val_lr, average="macro"))
print(classification_report(y_val, pred_val_lr, digits=4))

ConfusionMatrixDisplay.from_predictions(y_val, pred_val_lr)
plt.title("VAL Confusion Matrix - Logistic Regression")
plt.tight_layout()
plt.show()


# Model 2: Linear SVM

svm = LinearSVC(class_weight="balanced")
svm.fit(X_train, y_train)
pred_val_svm = svm.predict(X_val)

print("=== LinearSVC (VAL) ===")
print("Macro-F1:", f1_score(y_val, pred_val_svm, average="macro"))
print(classification_report(y_val, pred_val_svm, digits=4))

ConfusionMatrixDisplay.from_predictions(y_val, pred_val_svm)
plt.title("VAL Confusion Matrix - LinearSVC")
plt.tight_layout()
plt.show()


f1_lr  = f1_score(y_val, pred_val_lr, average="macro")
f1_svm = f1_score(y_val, pred_val_svm, average="macro")

if f1_lr >= f1_svm:
    best_name, best_model, best_val_pred = "LogReg", lr, pred_val_lr
else:
    best_name, best_model, best_val_pred = "LinearSVC", svm, pred_val_svm

print(f"\nBest model on VAL: {best_name} | Macro-F1: {max(f1_lr, f1_svm):.4f}")

from sklearn.metrics import f1_score, classification_report, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

if "label" in test_df.columns:
    y_test = test_df["label"].astype(int)
    pred_test = best_model.predict(X_test)

    print(f"\n=== {best_name} (TEST) ===")
    print("Macro-F1:", f1_score(y_test, pred_test, average="macro"))
    print(classification_report(y_test, pred_test, digits=4))

    ConfusionMatrixDisplay.from_predictions(y_test, pred_test)
    plt.title(f"TEST Confusion Matrix - {best_name}")
    plt.tight_layout()
    plt.show()

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.metrics import f1_score

tfidf = TfidfVectorizer(
    analyzer="char_wb",
    ngram_range=(3,5),
    min_df=2,
    max_features=200000
)

X_train = tfidf.fit_transform(train_df["text"])
X_val   = tfidf.transform(val_df["text"])

y_train = train_df["label"].astype(int)
y_val   = val_df["label"].astype(int)

svm = LinearSVC(class_weight="balanced", C=1.0)
svm.fit(X_train, y_train)

pred = svm.predict(X_val)
print("VAL macro-F1:", f1_score(y_val, pred, average="macro"))

from sklearn.linear_model import SGDClassifier
from sklearn.metrics import f1_score

clf = SGDClassifier(loss="log_loss", alpha=1e-5, max_iter=3000, class_weight="balanced")
clf.fit(X_train, y_train)
pred = clf.predict(X_val)
print("VAL macro-F1:", f1_score(y_val, pred, average="macro"))